PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/accounts/urls.py
from django.urls import path, include
from my_plants_app.accounts import views

urlpatterns = [
    path('profile/', include([
        path('create/', views.profile_create, name='profile create'),
        path('edit/', views.profile_edit, name='profile edit'),
        path('details/', views.profile_details, name='profile details'),
        path('delete/', views.profile_delete, name='profile delete'),
    ]))
]

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/common/urls.py
from django.urls import path, include

from my_plants_app.common import views

urlpatterns = [
    path('', views.index, name='index'),
    path('catalogue/', views.catalogue, name='catalogue')
]

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/urls.py
from django.urls import path, include
from my_plants_app.plants import views

urlpatterns = [
    path('create/', views.plant_create, name='plant create'),
    path('edit/<int:pk>/', views.plant_edit, name='plant edit'),
    path('details/<int:pk>/', views.plant_details, name='plant details'),
    path('delete/<int:pk>/', views.plant_delete, name='delete plant'),
]

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_plants_app.common.urls')),
    path('', include('my_plants_app.plants.urls')),
    path('profile/', include('my_plants_app.accounts.urls')),
]

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/accounts/models.py
from django.core import validators
from django.db import models
from my_plants_app.accounts.validators import validate_first_letter_capital


class Profile(models.Model):
    NAME_MAX_LEN = 20
    USERNAME_MAX_LEN = 10
    USERNAME_MIN_LEN = 2

    username = models.CharField(
        max_length=USERNAME_MAX_LEN,
        validators=[
            validators.MinLengthValidator(USERNAME_MIN_LEN),
        ],
    )

    first_name = models.CharField(
        max_length=NAME_MAX_LEN,
        validators=[
            validate_first_letter_capital,
        ]
    )

    last_name = models.CharField(
        max_length=NAME_MAX_LEN,
        validators=[
            validate_first_letter_capital,
        ]
    )

    profile_picture = models.URLField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return f'{self.username} : {self.first_name} {self.last_name}'
    

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/common/models.py
from django.db import models

# Create your models here.

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/models.py
from django.core import validators
from django.db import models
from my_plants_app.plants.validators import validate_name_contains_only_letters


class Plant(models.Model):
    PLANT_TYPE_MAX_LEN = 14
    NAME_MAX_LEN = 20
    NAME_MIN_LEN = 2

    PLANT_CHOICES = (
        ("Outdoor", "Outdoor Plants"),
        ("Indoor", "Indoor Plants"),
    )

    plant_type = models.CharField(
        max_length=PLANT_TYPE_MAX_LEN,
        choices=PLANT_CHOICES,
        verbose_name='Type',
    )

    name = models.CharField(
        max_length=PLANT_TYPE_MAX_LEN,
        validators=[
            validators.MinLengthValidator(NAME_MIN_LEN),
            validate_name_contains_only_letters,
        ]
    )

    image_URL = models.URLField()

    description = models.TextField()

    price = models.FloatField()

    def __str__(self):
        return f'{self.name} - type: {self.plant_type} '

    class Meta:
        ordering = ['pk']

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/accounts/forms.py
from django import forms

from my_plants_app.accounts.models import Profile


class ProfileBaseForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['profile_picture']

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/forms.py
from django import forms

from my_plants_app.plants.models import Plant


class PlantForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = '__all__'
        widgets = {
            'plant_type': forms.Select(),
            'name': forms.TextInput(),
            'image_URL': forms.URLInput(),
            'description': forms.Textarea(),
            'price': forms.NumberInput()
        }


class PlantDeleteForm(PlantForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'
            field.widget.attrs['readonly'] = 'readonly'

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/accounts/views.py
from django.shortcuts import render, redirect

from my_plants_app.accounts.forms import ProfileForm, ProfileBaseForm
from my_plants_app.accounts.models import Profile
from my_plants_app.common.views import add_user_to_context
from my_plants_app.plants.models import Plant


def profile_create(request):
    form = ProfileForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('catalogue')

    context = {
        'form': form,
    }

    return render(request, 'create-profile.html', context=add_user_to_context(context))


def profile_details(request):
    plants_count = Plant.objects.all().count()
    context = {
        'plants_count': plants_count,
    }
    return render(request, 'profile-details.html', context=add_user_to_context(context))


def profile_edit(request):
    profile = Profile.objects.first()
    form = ProfileBaseForm(request.POST or None, instance=profile)
    if form.is_valid():
        form.save()
        return redirect('profile details')

    context = {
        'form': form,
    }

    return render(request, 'edit-profile.html', context=add_user_to_context(context))


def profile_delete(request):
    profile = Profile.objects.first()

    if request.method == 'POST':
        profile.delete()
        Plant.objects.all().delete()
        return redirect('index')

    context = {}

    return render(request, 'delete-profile.html', context=add_user_to_context(context))

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/common/views.py
from django.shortcuts import render

from my_plants_app.accounts.models import Profile
from my_plants_app.plants.models import Plant


def add_user_to_context(context):
    profile = Profile.objects.first()
    context['profile'] = profile
    return context


def index(request):
    context = {

    }
    return render(request, 'home-page.html', context=add_user_to_context(context))


def catalogue(request):
    all_plants = Plant.objects.all()
    context = {
        'all_plants': all_plants,
    }
    return render(request, 'catalogue.html', context=add_user_to_context(context))

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/views.py
from django.shortcuts import render, redirect

from my_plants_app.common.views import add_user_to_context
from my_plants_app.plants.forms import PlantForm, PlantDeleteForm
from my_plants_app.plants.models import Plant


def plant_create(request):
    form = PlantForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('catalogue')

    context = {
        'form': form,
    }

    return render(request, 'create-plant.html', context=add_user_to_context(context))


def plant_edit(request, pk):
    plant = Plant.objects.get(pk=pk)
    form = PlantForm(request.POST or None, instance=plant)

    if form.is_valid():
        form.save()
        return redirect('catalogue')

    context = {
        'form': form,
    }
    return render(request, 'edit-plant.html', context=add_user_to_context(context))


def plant_details(request, pk):
    plant = Plant.objects.get(pk=pk)
    context = {
        'plant': plant,
    }

    return render(request, 'plant-details.html', context=add_user_to_context(context))


def plant_delete(request, pk):
    plant = Plant.objects.get(pk=pk)
    form = PlantDeleteForm(request.POST or None, instance=plant)

    if request.method == 'POST':
        plant.delete()
        return redirect('catalogue')

    context = {
        'form': form,
    }
    return render(request, 'delete-plant.html', context=add_user_to_context(context))

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/common/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/style.css' %}"/>
    <title>MyPlantApp</title>
</head>

<body>
<div id="box">
    <header>
        <!-- Navigation Bar -->
        <h1><a class="index-navigation" href="{% url 'index' %}">MyPlants</a></h1>
        <nav>
            <!-- if the user has not created a profile -->
            {% if not profile %}

                <a href="{% url 'profile create' %}">Create Profile</a>

            <!-- if the user has created a profile -->
            {% else %}


                <a href="{% url 'catalogue' %}">Catalogue</a>
                <a href="{% url 'plant create' %}">Create Plant</a>
                <a href="{% url 'profile details' %}">Profile</a>

            {% endif %}
        </nav>
    </header>

        {% block content %}
        {% endblock %}

    <footer>
        &copy;SoftUni Team 2022. All rights reserved.
    </footer>

</div>
</body>
</html>

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/common/templates/catalogue.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% if not all_plants  %}
    <!-- Display paragraph: If there are no plants yet-->
        <p class="no-articles">No plants yet</p>

    {% else %}
        <!-- Display div "plant" with information about every plant (if any)-->
        <section id="catalogue">

        {% for plant in all_plants %}

                <!-- first plant-->
                <div class="plant-card">
                    <div class="image-wrap">
                        <!-- plant image -->
                        <img src="{{ plant.image_URL }}"
                             alt="Indoor Plants">
                    </div>
                    <!-- plant name -->
                    <h3>{{ plant.name }}</h3>
                    <!-- plant description -->
                    <h1>{{  plant.description|truncatechars:20}} </h1>
                    <div class="details-buttons">
                        <!-- plant details button -->
                        <a href="{% url 'plant details' plant.pk %}" class="details-btn">Details</a>
                    </div>
                </div>

        {% endfor %}

        </section>

    {% endif %}

{% endblock %}

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/common/templates/home-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- headlines -->
    <section id="index-headline">
        <div class="index-message">
            <h2>When there is plant</h2>
            <h3>there is live</h3>
            <h4>Join us now!</h4>
        </div>

    </section>

 {% endblock %}

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/templates/create-plant.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- create plant form -->
    <section id="create-page" class="auth">
        <form method="POST" id="create">
            <div class="container">
                <h1 class="form-create-headline">Create Plant</h1>

                {% csrf_token %}
                {{ form }}

{#                <label for="type">Type:</label>#}
{#                <select name="type" required="" id="type">#}
{#                    <option value="" selected="">---------</option>#}
{#                    <option value="Outdoor Plants">Outdoor Plants</option>#}
{#                    <option value="Indoor Plants">Indoor Plants</option>#}
{#                </select>#}
{##}
{#                <label for="name">Name:</label>#}
{#                <input type="text" name="name" maxlength="20" required="" id="name">#}
{##}
{#                <label for="image_url">Image URL:</label>#}
{#                <input type="url" name="image_url" maxlength="200" required="" id="image_url">#}
{##}
{#                <label for="id_description">Description:</label>#}
{#                <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input type="number" name="price" required="" id="price">#}

                <input class="btn" type="submit" value="Create Plant">

            </div>
        </form>
    </section>


{% endblock %}

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/templates/delete-plant.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- delete plant form -->
    <section id="delete-page" class="auth">
        <form method="POST" id="delete">
            <div class="container">
                <h1>Delete Plant</h1>

                {% csrf_token %}
                {{ form }}

{#                <label for="type">Type:</label>#}
{#                <select name="type" disabled="disabled" readonly="readonly" required="" id="type">#}
{#                    <option value="">---------</option>#}
{#                    <option value="Outdoor Plants">Outdoor Plants</option>#}
{#                    <option value="Indoor Plants" selected="">Indoor Plants</option>#}
{#                </select>#}
{##}
{#                <label for="name">Name:</label>#}
{#                <input type="text" name="name" value="Orchid" maxlength="20" disabled="disabled" readonly="readonly" required="" id="name">#}
{##}
{#                <label for="image_url">Image URL:</label>#}
{#                <input type="url" name="image_url" value="https://www.ikea.com/om/en/images/products/fejka-artificial-potted-plant-orchid-white__0748880_pe745269_s5.jpg?f=s" maxlength="200" disabled="disabled" readonly="readonly" required="" id="image_url">#}
{##}
{#                <label for="id_description">Description:</label>#}
{#                <textarea name="description" cols="40" rows="10" disabled="disabled" readonly="readonly" required="" id="id_description">Orchids are plants that belong to the family Orchidaceae, a diverse and widespread group of flowering plants with blooms that are often colourful and fragrant.</textarea>#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input type="number" name="price" value="10.0" disabled="disabled" readonly="readonly" required="" id="price">#}

                <input class="btn submit" type="submit" value="Delete Plant">

            </div>
        </form>
    </section>
{% endblock %}

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/templates/edit-plant.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- edit plant form -->
    <section id="create-page" class="auth">
        <form method="POST" id="create">
            <div class="container">
                <h1>Edit Plant</h1>

                {% csrf_token %}
                {{ form }}

{#                <label for="type">Type:</label>#}
{#                <select name="type" required="" id="type">#}
{#                    <option value="">---------</option>#}
{#                    <option value="Outdoor Plants">Outdoor Plants</option>#}
{#                    <option value="Indoor Plants" selected="">Indoor Plants</option>#}
{#                </select>#}
{##}
{#                <label for="name">Name:</label>#}
{#                <input type="text" name="name" value="Orchid" maxlength="20" required="" id="name">#}
{##}
{#                <label for="image_url">Image URL:</label>#}
{#                <input type="url" name="image_url" value="https://www.ikea.com/om/en/images/products/fejka-artificial-potted-plant-orchid-white__0748880_pe745269_s5.jpg?f=s" maxlength="200" required="" id="image_url">#}
{##}
{#                <label for="id_description">Description:</label>#}
{#                <textarea name="description" cols="40" rows="10" required="" id="id_description">Orchids are plants that belong to the family Orchidaceae, a diverse and widespread group of flowering plants with blooms that are often colourful and fragrant.</textarea>#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input type="number" name="price" value="10.0" required="" id="price">#}

                <input class="btn submit" type="submit" value="Edit Plant">
            </div>
        </form>
    </section>

{% endblock %}

PYTHON WEB BASICS/Django_projects/my_plants_app/my_plants_app/plants/templates/plant-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- details section -->
    <section id="plant-details">
        <h1>Plant Details</h1>
        <div class="info-section">
            <div class="plant-header">
                <!-- plant image -->
                <img class="plant-img"
                     src="{{ plant.image_URL }}"
                     alt='plant image'/>
                <!-- plant type -->
                <h1>{{ plant.plant_type }}</h1>
                <!-- plant name -->
                <p><span class="description-plant">Name: {{ plant.name }}</span></p>
                <!-- plant price -->
                <p><span class="description-plant">Price: {{ plant.price|floatformat:2 }}</span></p>
                <!-- plant description -->
                <p><span class="description-plant">Description: {{ plant.description }}.</span></p>
            </div>

            <!-- Edit/Delete buttons -->
            <div class="buttons">
                <a href="{% url 'plant edit' plant.pk %}" class="edit-button">Edit</a>
                <a href="{% url 'delete plant' plant.pk %}" class="delete-button">Delete</a>
            </div>
        </div>
    </section>


{% endblock %}