PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/urls.py
from django.urls import path, include

from petstagram_2.accounts import views

import petstagram_2.accounts.signals

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', include([
        path('', views.UserDetailsView.as_view(), name='profile details'),
        path('edit/', views.UserEditView.as_view(), name='profile edit'),
        path('delete/', views.UserDeleteView.as_view(), name='profile delete'),
    ])),

]

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from petstagram_2 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram_2.common.urls')),
    path('accounts/', include('petstagram_2.accounts.urls')),
    path('pets/', include('petstagram_2.pets.urls')),
    path('photos/', include('petstagram_2.photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from petstagram_2.accounts.validators import validate_name_is_longer_then_two_cars, validate_name_isalpha


class PetstagramUser(AbstractUser):

    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Do not show', 'Do not show')
    )

    email = models.EmailField(
        unique=True
    )
    first_name = models.CharField(
        max_length=30,
        validators=[
            validate_name_is_longer_then_two_cars,
            validate_name_isalpha,
        ],
        null=True,
        blank=True,
    )
    last_name = models.CharField(
        max_length=30,
        validators=[
            validate_name_is_longer_then_two_cars,
            validate_name_isalpha,
        ],
        null=True,
        blank=True,
    )
    profile_picture = models.URLField(
        null=True,
        blank=True,
    )
    gender = models.CharField(
        max_length=12,
        choices=GENDER_CHOICES,
        default='Do not show',
        null=True,
        blank=True,
    )

    def get_user_name(self):
        if self.first_name and self.last_name:
            return f'{self.first_name} {self.last_name}'
        elif self.first_name or self.last_name:
            return self.first_name or self.last_name
        else:
            return self.username

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/pets/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify

from petstagram_2.accounts.models import PetstagramUser


USER_MODEL = get_user_model()


class Pet(models.Model):
    name = models.CharField(max_length=30)
    personal_photo = models.URLField()
    date_of_birth = models.DateField(blank=True, null=True)
    slug = models.SlugField(unique=True, editable=False)
    user = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f'{self.name}-{self.pk}')
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}  -  {self.slug}'

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/photos/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram_2.accounts.models import PetstagramUser
from petstagram_2.pets.models import Pet
from petstagram_2.photos.validators import file_size_validator


USER_MODEL = get_user_model()


class Photo(models.Model):
    photo = models.ImageField(
        upload_to='images/',
        validators=[
            file_size_validator,
        ]
    )
    description = models.TextField(
        max_length=300,
        validators=[
            MinLengthValidator(10)
        ],
        blank=True,
        null=True,
    )
    location = models.CharField(max_length=30, blank=True, null=True)
    tagged_pets = models.ManyToManyField(to=Pet, blank=True)
    date_of_publication = models.DateField(auto_now_add=True)
    user = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ['-date_of_publication', '-pk']

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django import forms

from petstagram_2.accounts.models import PetstagramUser


class PetstagramUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = PetstagramUser
        fields = ('username', 'email')


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'placeholder': 'Username',
            }
        )
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'current-password',
                'placeholder': 'Password',
            }
        )
    )


class PetstagramUserEditForm(forms.ModelForm):
    class Meta:
        model = PetstagramUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture', 'gender')
        exclude = ('password', )
        labels = {
            'username': 'Username',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email',
            'profile_picture': 'Profile Picture',
            'gender': 'Gender',
        }

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/views.py
import http

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import views as auth_views, login

from petstagram_2.accounts.forms import PetstagramUserCreationForm, LoginForm, PetstagramUserEditForm
from petstagram_2.accounts.models import PetstagramUser


class UserRegisterView(views.CreateView):
    model = PetstagramUser
    form_class = PetstagramUserCreationForm
    template_name = 'register-page.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        login(self.request, self.object)
        return result

    def get_context_data(self,  **kwargs):
        context = super().get_context_data(**kwargs)

        context['next'] = self.request.GET.get('next', None)

        return context

    def get_success_url(self):
        result = self.request.POST.get('next', None)
        print(result)
        if result == 'None':
            print('There is NO next!')
            return self.success_url
        return result


class LoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'login-page.html'
    next_page = reverse_lazy('index')


# @login_required
class UserLogoutView(LoginRequiredMixin, auth_views.LogoutView):
    http_method_names = ["post", "options", "get"]
    next_page = 'login'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class UserEditView(LoginRequiredMixin, views.UpdateView):
    model = PetstagramUser
    form_class = PetstagramUserEditForm
    template_name = 'profile-edit-page.html'

    def get_success_url(self):
        return reverse_lazy('profile details', kwargs={'pk': self.object.pk})


class UserDetailsView(LoginRequiredMixin, views.DetailView):
    model = PetstagramUser
    template_name = 'profile-details-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_likes_count = sum(p.like_set.count() for p in self.object.photo_set.all())
        profile_image = static('images/person.png')
        if self.object.profile_picture not in ['', None]:
            profile_image = self.object.profile_picture

        context.update({
            'total_likes_count': total_likes_count,
            'profile_image': profile_image,
        })

        return context


class UserDeleteView(LoginRequiredMixin, views.DeleteView):
    model = PetstagramUser
    template_name = 'profile-delete-page.html'
    success_url = reverse_lazy('index')

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        user.delete()
        return redirect(self.success_url)

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/templates/email-greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Petstagram</title>
</head>
<body style="display: flex;
			justify-content: center;">
<div style="display: flex;
			justify-content: center;
			border: 3px solid rgb(65, 63, 63);
			border-radius: 20px;
			margin: 2%;
			max-width: 620px;">
    <div>
		<table>
			<nav style="">
		<img style="width: 10rem;
			 margin-top: 10px;
			 margin-left: -4px;
			 height: 3.3rem;"
			 src="https://jdzejo.stripocdn.email/content/guids/3be6ad80-cf0f-461f-807a-b499c494e798/images/screenshot_1_roO.png"
			 alt="Logo">
	</nav>
		</table>

        <h1 style="			text-align: center;
                color: rgb(65, 63, 63);
                font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">

            <!-- Receiver username -->
            Hello, {{ user.username }} !</h1>

        <div style="display: flex;
                justify-content: center;">
            <img style="width: 70%;" id="cat-image"
                 src="https://jdzejo.stripocdn.email/content/guids/CABINET_b71dddfca1f6a4c91ed66e0fc480ad7f/images/ezgifcomgifmaker.gif"
                 alt="gif cat">
        </div>

        <p style="max-width: 620px;
            padding: 20px 20px 0 20px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            Congratulations on creating your profile at Petstagram.
            Our pets are our best friends, and we love them so much that we want to share every moment with them with
            the
            world.
            Let's make the biggest pet community!
        </p>
        <p style="max-width: 620px;
            padding: 20px 20px 0 20px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            Sincerely,
            <br>
            <img style="width: 30%;
            margin-top: 10px;
            margin-left: -4px;"
                 src="https://jdzejo.stripocdn.email/content/guids/3be6ad80-cf0f-461f-807a-b499c494e798/images/screenshot_1_roO.png"
                 alt="Logo">
        </p>
    </div>
</div>
</body>
</html>

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/templates/login-page.html
{% extends 'base.html' %}

{% block content %}
    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}

{#                <p>#}
{#                    <label for="id_username">Username:</label>#}
{#                    <input type="text" placeholder="Username">#}
{#                </p>#}
{#                <p>#}
{#                    <label for="id_password">Password:</label>#}
{#                    <input type="password" placeholder="Password">#}
{#                </p>#}

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have account? <a href="{% url 'register' %}?next={{ next }}">Register</a></p>
        </div>
    </div>
    <!-- End Login Section-->

{% endblock %}

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/templates/profile-delete-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>

            <form method="POST">
                {% csrf_token %}

                <div class="sure-buttons">
                    <!-- Yes (Delete Profile) Button -->
                    <button>Yes</button>
                    <!-- Go Back Button -->
                    <a class="edit-btn" href="javascript:history.back()">Go Back</a>
                </div>

            </form>


            <img src="{% static 'images/are_you_sure_cat.gif' %}" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->


{% endblock %}

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/templates/profile-details-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Start Profile Details Section -->
    <div class="profile">

        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
            <div class="profile_img">
                <div class="image">

                    <!-- Profile Image -->
{#                    {% if object.profile_picture %}#}
                        <img src="{{ profile_image }}" alt="img8">
{#                    {% else %}#}
{#                        <img src="{% static 'images/person.png' %}" alt="img8">#}
{#                    {% endif %}#}
                </div>
            </div>
            <div class="personal">
                <div class="edit">
                    <!-- User Username -->
                    <p>{{ object.username }}</p>

                    <!-- IF the viewer is the owner of the profile -->
                    {% if request.user == object %}
                    <!-- Link to Edit Profile Page -->
                    <a href="{% url 'profile edit' request.user.pk %}">
                        <img class="edit-img" src="/static/images/edit-pen-icon-6.jpg" alt="edit button">
                    </a>

                    <!-- Link to Delete Profile Page -->
                    <a href="{% url 'profile delete' request.user.pk %}">
                        <img class="bin-img" src="/static/images/icon-remove-22.jpg" alt="bin button">
                    </a>
                    {% endif %}
                    <!-- End IF the viewer is the owner of the profile -->

                </div>
                <div class="data">

                    <!-- Total Number of Photos by the User -->
                    <span>{{ object.photo_set.count }}</span>
                    <p>photos</p>

                    <!-- Total Number of Pets owned by the User -->
                    <span>{{ object.pet_set.count }}</span>
                    <p>pets</p>

                    <!-- Total Number of Likes for the User -->
                    <span>{{ total_likes_count }}</span>
                    <p>likes</p>
                </div>
                <!-- User First and Last Name IF Added -->
                <h3 class="names">{{ object.get_user_name}}</h3>

                <!-- User Email Address -->
                <p class="email">{{ object.email }}</p>

                <!-- User Gender IF Added -->
                <p class="gender">{{ object.gender }}</p>
            </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
            <div class="statuses">

                {% for pet in object.pet_set.all  %}

                <!-- Start 1st Pet Details Page -->
                <!-- Link to First Pet Details Page -->
                <a href="{% url 'pet details' object.username pet.slug %}">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <!-- Pet Image -->
                                <img src="{{ pet.personal_photo }}"
                                     alt="pet img">
                            </div>
                        </div>
                        <!-- Pet Name -->
                        <p>{{ pet.name }}</p>
                    </div>
                </a>
                <!-- End 1st Pet Details Page -->

                {% endfor %}


{##}
{#                <!-- Start 2nd Pet Details Page -->#}
{#                <!-- Link to Second Pet Details Page -->#}
{#                <a href="{% url 'pet details' 'doncho' 'sasho'%}">#}
{#                    <div class="head-pet">#}
{#                        <div class="status">#}
{#                            <div class="image">#}
{#                                <!-- Pet Image -->#}
{#                                <img src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313__340.jpg"#}
{#                                     alt="pet img">#}
{#                            </div>#}
{#                        </div>#}
{#                        <!-- Pet Name -->#}
{#                        <p>Todi</p>#}
{#                    </div>#}
{#                </a>#}
{#                <!-- End 2nd Pet Details Page -->#}
{##}
{#                <!-- Start 3rd Pet Details Page -->#}
{#                <!-- Link to Pet Details Page -->#}
{#                <a href="{% url 'pet details' 'doncho' 'sasho'%}">#}
{#                    <div class="head-pet">#}
{#                        <div class="status">#}
{#                            <div class="image">#}
{#                                <img src="https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGRvZ3xlbnwwfHwwfHw%3D&w=1000&q=80"#}
{#                                     alt="pet img">#}
{#                            </div>#}
{#                        </div>#}
{#                        <p>Mihail</p>#}
{#                    </div>#}
{#                </a>#}
{#                <!-- End 3rd Pet Details Page -->#}
{##}
{#                <!-- Start 4th Pet Details Page -->#}
{#                <!-- Link to Pet Details Page -->#}
{#                <a href="{% url 'pet details' 'doncho' 'sasho'%}">#}
{#                    <div class="head-pet">#}
{#                        <div class="status">#}
{#                            <div class="image">#}
{#                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"#}
{#                                     alt="pet img">#}
{#                            </div>#}
{#                        </div>#}
{#                        <p>Petar</p>#}
{#                    </div>#}
{#                </a>#}
{#                <!-- End 4th Pet Details Page -->#}
{##}
{#                <!-- Start 5th Pet Details Page -->#}
{#                <!-- Link to Pet Details Page -->#}
{#                <a href="{% url 'pet details' 'doncho' 'sasho'%}">#}
{#                    <div class="head-pet">#}
{#                        <div class="status">#}
{#                            <div class="image">#}
{#                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdKYe00NaD5SQjIMvXYPssq0r1dXJggL3ZIg&usqp=CAU"#}
{#                                     alt="pet img">#}
{#                            </div>#}
{#                        </div>#}
{#                        <p>Stamat</p>#}
{#                    </div>#}
{#                </a>#}
{#                <!-- End 5th Pet Details Page -->#}
{##}
{#                <!-- Start 6th Pet Details Page -->#}
{#                <!-- Link to Pet Details Page -->#}
{#                <a href="{% url 'pet details' 'doncho' 'sasho'%}">#}
{#                    <div class="head-pet">#}
{#                        <div class="status">#}
{#                            <div class="image">#}
{#                                <img src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"#}
{#                                     alt="pet img">#}
{#                            </div>#}
{#                        </div>#}
{#                        <p>Toni</p>#}
{#                    </div>#}
{#                </a>#}
{#                <!-- End 6th Pet Details Page -->#}
{##}
{#                <!-- Start 7th Pet Details Page -->#}
{#                <!-- Link to Pet Details Page -->#}
{#                <a href="{% url 'pet details' 'doncho' 'sasho'%}">#}
{#                    <div class="head-pet">#}
{#                        <div class="status">#}
{#                            <div class="image">#}
{#                                <img src="https://i.pinimg.com/736x/01/6f/72/016f72c5812e1b8f71bdbf19d8c7558b.jpg"#}
{#                                     alt="pet img">#}
{#                            </div>#}
{#                        </div>#}
{#                        <p>Daisy</p>#}
{#                    </div>#}
{#                </a>#}
{#                <!-- End 7th Pet Details Page -->#}

            </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">

            {% for photo in object.photo_set.all %}

            <!-- Link to Last Uploaded Pet Photo -->
            <a href="{% url 'photo details' photo.pk %}">
                <!-- Pet Photo -->
                <img src="{{ photo.photo.url }}"
                     alt="pet img">
            </a>

            {% endfor %}

{#            <!-- Link to Uploaded Pet Photo -->#}
{#            <a href="{% url 'photo details' 1 %}">#}
{#                <!-- Pet Photo -->#}
{#                <img src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"#}
{#                     alt="pet img">#}
{#            </a>#}
{##}
{#            <!-- Link to Uploaded Pet Photo -->#}
{#            <a href="{% url 'photo details' 1 %}">#}
{#                <!-- Pet Photo -->#}
{#                <img src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg" alt="pet img">#}
{#            </a>#}
{##}
{#            <!-- Link to  Uploaded Pet Photo -->#}
{#            <a href="{% url 'photo details' 1 %}">#}
{#                <!-- Pet Photo -->#}
{#                <img src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png" alt="pet img">#}
{#            </a>#}
        </div>
        <!-- End Last Uploaded Photos Section -->

    </div>
    <!-- End Profile Details Section -->
{% endblock %}

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/templates/profile-edit-page.html
{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{##}
{#    <!-- Start Edit Profile Section -->#}
{#    <div class="edit-delete">#}
{#        <h2>Edit Profile</h2>#}
{#        <!-- Start Edit Profile From -->#}
{#        <form method="POST">#}
{#            <div class="label-input">#}
{#                <label for="first name">First name: </label>#}
{#                <input type="text" placeholder="First name" value="Diyan">#}
{#            </div>#}
{#            <br>#}
{#            <div class="label-input">#}
{#                <label for="last name">Last name: </label>#}
{#                <input type="text" placeholder="Last name" value="Kalayadzhiev">#}
{#            </div>#}
{#            <br>#}
{#            <div class="label-input">#}
{#                <label for="username">Username: </label>#}
{#                <input type="text" placeholder="Username" value="k_dido">#}
{#            </div>#}
{#            <br>#}
{#            <div class="label-input">#}
{#                <label for="email">Email: </label>#}
{#                <input type="email" placeholder="Email" value="d.denov@gmail.com">#}
{#            </div>#}
{#            <br>#}
{#            <div class="label-input">#}
{#                <label for="image">Image: </label>#}
{#                <input type="text" placeholder="Link to to profile picture"#}
{#                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">#}
{#            </div>#}
{#            <br>#}
{##}
{#            <div class="label-input">#}
{#                <label for="image">Gender: </label>#}
{#                <div class="list-choice">#}
{#                    <div class="list-choice-title">Gender</div>#}
{#                    <div class="list-choice-objects">#}
{#                        <label>#}
{#                            <input type="radio" name="gender"/> <span>Male</span>#}
{#                        </label>#}
{#                        <label>#}
{#                            <input type="radio" name="gender"/> <span>Female</span>#}
{#                        </label>#}
{#                        <label>#}
{#                            <input type="radio" name="gender"/> <span>Do not show</span>#}
{#                        </label>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <!-- Edit Profile Button -->#}
{#            <button class="edit-btn" type="submit">Edit</button>#}
{#        </form>#}
{#        <!-- End Edit Profile Form -->#}
{##}
{#    </div>#}
{#    <!-- End Edit Profile Section -->#}
{##}
{#    {% endblock %}#}

{% extends 'base.html' %}
{% block content %}

    <!-- Start Edit Profile Section -->

    <div class="edit-delete"><h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p class="error">
                    {{ field.errors }}
                </p>

            <div class="label-input">
                <label>{{ field.label }}</label>

                {% if not field.label == "Gender:" %}
                    {{ field }}
                {% else %}
                    <div class="list-choice">
                        <div class="list-choice-title">Gender</div>
                        <div class="list-choice-objects">
                            {% for type, value in form.fields.gender.choices %}
                            <label> <input type="radio"
                                           value="{{ value }}"
                                           name="gender"
                                    {% if form.gender.value == value %}
                                           checked
                                    {% endif %}/>
                                <span>{{ value }}</span>
                            </label>

                            {% endfor %}
                        </div>
                    </div> {% endif %} </div> <br> {% endfor %} <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>

        <!-- End Edit Profile Form -->

    </div> <!-- End Edit Profile Section -->

{% endblock %}

PYTHON WEB BASICS/Django_projects/petstagram_2/petstagram_2/accounts/templates/register-page.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}

    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form method="POST">

                {% csrf_token %}
                {{ form.username.errors }}
                {{ form.username|placeholder:'Username' }}
                {{ form.email.errors }}
                {{ form.email|placeholder:'Email' }}
                {{ form.password1.errors }}
                {{ form.password2.errors }}
                {{ form.password1|placeholder:'Password' }}
                {{ form.password2|placeholder:'Repeat password' }}

                <input type="hidden" name="next" value = {{ next }}>

{#                <input type="text" placeholder="Username">#}
{##}
{#                <input type="email" placeholder="Email">#}
{##}
{#                <input type="password" placeholder="Password">#}
{##}
{#                <input type="password" placeholder="Repeat Password">#}

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="{% url 'login' %}">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->
{% endblock %}